### ISSUE TITLE
target(...).slice is not a function

### ISSUE THREAD

**Issue by odiego** [ErikSchierboom/knockout-paging#12]

**Comment by ErikSchierboom** [comment]
Hi,
I'm not sure I quite understand your problem. Where do you use my paging plugin? Could you perhaps send me some more code?
Cheers,
Erik

Date: Fri, 2 Oct 2015 12:18:32 -0700

**Comment by odiego** [comment]
Sorry Erik, it was a mistake.
The observableArray that was supposed to be paged was with a single element, and it was not a list.
Please close this issue.

**Comment by ErikSchierboom** [comment]
No problem!

Date: Fri, 2 Oct 2015 13:34:10 -0700
