### ISSUE TITLE
get data from Ajax on click of a page number

### ISSUE THREAD

**Issue by gsvitak** [ErikSchierboom/knockout-paging#18]
Hello,

Thanks for the work.. it is pretty awesome and easy to use. 

I have a question to see if you might be able to suggest how I could modify the extended to support calling an AJAX endpoint when clicking on one of the pages. I only want to load in 15 objects and then load the correct 15 when the user selects the appropriate page.

Any suggestions would be appreciated.

Thanks
G

**Comment by ErikSchierboom** [comment]
Hi. To support that scenario, I think it would require a bit of refactoring I think. There are several things that should change:

1. You should be able to specify the total number of items when creating the paged instance. The [`itemCount` function](https://github.com/ErikSchierboom/knockout-paging/blob/master/knockout-paging.js#L176) should then return that value, not dynamically compute it.
2. The initialization options should also pass in a function to call with which to retrieve the page items.
3. Setting the page number should call the function from step 2. The result should then be stored locally.

The biggest problem I see is that suddenly things start getting asynchronous. You can't just get the value of a page, you can only get a promise. That means changing the API and making sure Knockout correctly handles asynchronous observables. That's not entirely trivial unfortunately, as [this article](https://github.com/knockout/knockout/wiki/asynchronous-dependent-observables) shows.

Hope this helps! If you need any further help, let me know.

**Comment by ErikSchierboom** [comment]
I'm gonna close this issue due to inactivity.
